const API = window.API_BASE_URL || (location.hostname === 'localhost' ? 'http://localhost:8000/api/v1' : 'https://ideal-marcenaria-api.onrender.com/api/v1');
const $ = (s, root = document) => root.querySelector(s);
const $$ = (s, root = document) => [...root.querySelectorAll(s)];
const state = { user:null, resource:null, id:null, rows:[], categories:[], customers:[], search:'' };
const labels = {dashboard:'Dashboard',customers:'Clientes',quotes:'Orçamentos',products:'Produtos / projetos',categories:'Serviços & categorias',users:'Usuários'};
const statusLabels = {pending:'Pendente',approved:'Aprovado',rejected:'Recusado'};
const csrf = () => document.cookie.split('; ').find(x=>x.startsWith('csrf_token='))?.split('=')[1] || '';
const escapeHtml = (v='') => String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const money = v => Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
function toast(message,type='success'){const el=$('#toast');if(!el)return;el.textContent=message;el.className=`toast show ${type}`;clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.className='toast',3500)}
async function api(path,options={}){const opts={credentials:'include',...options,headers:{...(options.headers||{})}};if(opts.body&&!(opts.body instanceof URLSearchParams)&&typeof opts.body!=='string'){opts.headers['Content-Type']='application/json';opts.body=JSON.stringify(opts.body)}if(['POST','PUT','PATCH','DELETE'].includes(opts.method)&&csrf())opts.headers['X-CSRF-Token']=csrf();const res=await fetch(API+path,opts);if(res.status===204)return null;const data=await res.json().catch(()=>({}));if(!res.ok)throw new Error(data.detail||(res.status===401?'Sessão expirada. Faça login novamente.':`Erro ${res.status}`));return data}
function openAuth(view='login'){const o=$('#auth-overlay');o.classList.remove('hidden');o.setAttribute('aria-hidden','false');showAuth(view)}
function closeAuth(){const o=$('#auth-overlay');o.classList.add('hidden');o.setAttribute('aria-hidden','true')}
function showAuth(view){['login','register','recovery'].forEach(v=>$(`#${v}-view`).classList.toggle('hidden',v!==view))}
function getWhatsApp(){return window.WHATSAPP_NUMBER||''}
function showWhatsApp(message=''){const number=getWhatsApp();if(number){window.open(`https://wa.me/${number}?text=${encodeURIComponent(message)}`,'_blank','noopener')}else{alert('O site está pronto. Configure o número de WhatsApp da Marcenaria Ideal em window.WHATSAPP_NUMBER para ativar este botão.')}}
function setupPublic(){$$('#open-login').forEach(b=>b.addEventListener('click',()=>openAuth('login')));$('#close-auth').addEventListener('click',closeAuth);$('#auth-overlay').addEventListener('click',e=>{if(e.target.id==='auth-overlay')closeAuth()});$$('[data-quote]').forEach(b=>b.addEventListener('click',()=>showWhatsApp('Olá! Quero solicitar um orçamento para móveis planejados.')));$$('.whatsapp').forEach(b=>b.addEventListener('click',e=>{if(!getWhatsApp()){e.preventDefault();showWhatsApp()}}));$('#show-register').addEventListener('click',()=>showAuth('register'));$('#show-recovery').addEventListener('click',()=>showAuth('recovery'));$$('[data-auth-back]').forEach(b=>b.addEventListener('click',()=>showAuth('login')));$('#login-form').addEventListener('submit',login);$('#register-form').addEventListener('submit',register);$('#recovery-form').addEventListener('submit',recovery)}
async function login(e){e.preventDefault();$('#login-error').textContent='';try{const body=new URLSearchParams({username:$('#login-email').value.trim().toLowerCase(),password:$('#login-password').value});await api('/auth/login',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body});state.user=await api('/me');if(!state.user.is_admin)throw new Error('Sua conta foi criada, mas ainda não possui permissão administrativa.');closeAuth();enterAdmin()}catch(err){$('#login-error').textContent=err.message;if(err.message.includes('permissão'))await api('/auth/logout',{method:'POST'}).catch(()=>{})}}
async function register(e){e.preventDefault();const msg=$('#register-message');msg.className='form-message';msg.textContent='';try{await api('/auth/register',{method:'POST',body:{name:$('#register-name').value.trim(),email:$('#register-email').value.trim().toLowerCase(),password:$('#register-password').value}});msg.classList.add('success');msg.textContent='Cadastro realizado! Agora faça login.';e.target.reset();setTimeout(()=>showAuth('login'),700)}catch(err){msg.classList.add('error');msg.textContent=err.message}}
async function recovery(e){e.preventDefault();const email=$('#recovery-email').value.trim().toLowerCase();toast('Para redefinir a senha, fale com a equipe pelo WhatsApp.');e.target.reset();console.info('Recovery requested for',email);setTimeout(()=>showAuth('login'),500)}
function enterAdmin(){$('#public-site').classList.add('hidden');$('#admin-app').classList.remove('hidden');$('#user-badge').textContent=state.user?.name||'Administrador';loadDashboard()}
async function logout(){try{await api('/auth/logout',{method:'POST'})}finally{location.reload()}}
function setupAdmin(){$$('#admin-nav .nav').forEach(b=>b.addEventListener('click',()=>showSection(b.dataset.section)));$('#logout').addEventListener('click',logout);$('#modal-close').addEventListener('click',closeModal);$('#modal').addEventListener('click',e=>{if(e.target.id==='modal')closeModal()});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});$('#item-form').addEventListener('submit',submitItem);$('#theme-toggle').addEventListener('click',()=>{document.body.classList.toggle('dark');localStorage.setItem('ideal-theme',document.body.classList.contains('dark')?'dark':'light')});if(localStorage.getItem('ideal-theme')==='dark')document.body.classList.add('dark')}
function showSection(name){$$('.admin-section').forEach(s=>s.classList.add('hidden'));$(`#${name}`).classList.remove('hidden');$$('#admin-nav .nav').forEach(b=>b.classList.toggle('active',b.dataset.section===name));$('#admin-title').textContent=labels[name]||'Dashboard';if(name==='dashboard')loadDashboard();else loadResource(name)}
async function loadDashboard(){const section=$('#dashboard');section.innerHTML='<div class="panel loading">Carregando visão geral...</div>';try{const [data,me]=await Promise.all([api('/admin/dashboard'),api('/me')]);state.user=me;$('#user-badge').textContent=me.name;const c=data.counts||{};const cards=[['Clientes',c.customers||0,'customers'],['Orçamentos',c.quotes||0,'quotes'],['Produtos',c.products||0,'products'],['Categorias',c.categories||0,'categories'],['Usuários',c.users||0,'users']];section.innerHTML=`<div class="welcome"><div><span class="eyebrow">Visão geral</span><h2>Olá, ${escapeHtml(me.name.split(' ')[0])}. 👋</h2><p>Seu painel da Marcenaria Ideal está conectado à API e ao PostgreSQL.</p></div><button class="btn light" onclick="showSection('quotes')">Novo orçamento</button></div><div class="stats">${cards.map(([n,v,s])=>`<button class="stat" onclick="showSection('${s}')"><span>${n}</span><strong>${v}</strong><small>Gerenciar ${n.toLowerCase()} →</small></button>`).join('')}</div><div class="panel"><div class="panel-title"><div><span class="eyebrow">Status</span><h3>Sistema operacional</h3></div><span class="badge success">Online</span></div><p class="muted">Autenticação, sessão por cookies seguros, proteção CSRF, API FastAPI e PostgreSQL estão integrados.</p></div>`}catch(err){section.innerHTML=`<div class="panel empty"><h2>Não foi possível carregar o painel</h2><p>${escapeHtml(err.message)}</p><button class="btn primary" onclick="loadDashboard()">Tentar novamente</button></div>`}}
const configs={customers:{title:'Clientes',endpoint:'/customers',columns:[['name','Cliente'],['email','E-mail'],['phone','Telefone'],['address','Endereço']],empty:'Nenhum cliente cadastrado.'},quotes:{title:'Orçamentos',endpoint:'/quotes',columns:[['customer_id','Cliente'],['description','Descrição'],['total','Valor'],['status','Status']],empty:'Nenhum orçamento cadastrado.'},products:{title:'Produtos / projetos',endpoint:'/products',columns:[['name','Nome'],['category_id','Categoria'],['price','Valor'],['is_active','Status']],empty:'Nenhum produto cadastrado.'},categories:{title:'Serviços & categorias',endpoint:'/categories',columns:[['name','Nome'],['description','Descrição']],empty:'Nenhuma categoria cadastrada.'},users:{title:'Usuários',endpoint:'/admin/users',columns:[['name','Nome'],['email','E-mail'],['is_admin','Permissão'],['is_active','Status']],empty:'Nenhum usuário cadastrado.'}};
async function loadResource(resource){const cfg=configs[resource],section=$(`#${resource}`);state.search='';section.innerHTML='<div class="panel loading">Carregando...</div>';try{if(resource==='products')state.categories=await api('/categories?limit=100');if(resource==='quotes')state.customers=await api('/customers?limit=100');state.rows=await api(`${cfg.endpoint}?limit=100`);renderResource(resource)}catch(err){section.innerHTML=`<div class="panel empty"><h2>Não foi possível carregar</h2><p>${escapeHtml(err.message)}</p><button class="btn primary" onclick="loadResource('${resource}')">Tentar novamente</button></div>`}}
function renderResource(resource){const cfg=configs[resource],section=$(`#${resource}`),rows=state.rows.filter(row=>!state.search||Object.values(row).some(v=>String(v??'').toLowerCase().includes(state.search.toLowerCase())));const head=cfg.columns.map(c=>`<th>${c[1]}</th>`).join('');const body=rows.length?rows.map(row=>`<tr>${cfg.columns.map(([k])=>`<td>${formatCell(resource,k,row[k])}</td>`).join('')}<td class="actions">${resource==='users'?`<button class="small-btn" onclick="editItem('users',${row.id})">Editar</button>`:`<button class="small-btn" onclick="editItem('${resource}',${row.id})">Editar</button><button class="small-btn danger" onclick="deleteItem('${resource}',${row.id})">Excluir</button>`}</td></tr>`).join(''):`<tr><td colspan="${cfg.columns.length+1}" class="empty-row">${cfg.empty}</td></tr>`;const createButton=resource==='users'?'':`<button class="btn primary" onclick="createItem('${resource}')">+ Novo</button>`;section.innerHTML=`<div class="panel"><div class="toolbar"><div><span class="eyebrow">Gerenciamento</span><h2>${cfg.title}</h2><p>${rows.length} registro(s)</p></div><div class="toolbar-actions"><input id="search-${resource}" placeholder="Pesquisar..." value="${escapeHtml(state.search)}" oninput="setSearch('${resource}',this.value)">${createButton}</div></div><div class="table-wrap"><table class="table"><thead><tr>${head}<th>Ações</th></tr></thead><tbody>${body}</tbody></table></div></div>`}
function setSearch(resource,value){state.search=value;renderResource(resource);const input=$(`#search-${resource}`);if(input){input.focus();input.setSelectionRange(value.length,value.length)}}
function formatCell(resource,key,value){if(value===null||value===undefined||value==='')return'<span class="muted">—</span>';if(key==='price'||key==='total')return money(value);if(key==='is_admin')return value?'<span class="badge success">Administrador</span>':'<span class="badge">Usuário</span>';if(key==='is_active')return value?'<span class="badge success">Ativo</span>':'<span class="badge">Inativo</span>';if(key==='status')return`<span class="badge">${escapeHtml(statusLabels[value]||value)}</span>`;if(key==='category_id')return escapeHtml(state.categories.find(x=>x.id===value)?.name||`#${value}`);if(key==='customer_id')return escapeHtml(state.customers.find(x=>x.id===value)?.name||`#${value}`);return escapeHtml(value)}
function field(label,name,type='text',value='',required=false,extra=''){return`<label>${label}${type==='textarea'?`<textarea name="${name}" ${required?'required':''} ${extra}>${escapeHtml(value)}</textarea>`:`<input name="${name}" type="${type}" value="${escapeHtml(value)}" ${required?'required':''} ${extra}>`}</label>`}
function selectField(label,name,options,value=''){return`<label>${label}<select name="${name}" required><option value="">Selecione...</option>${options.map(o=>`<option value="${o.id}" ${String(o.id)===String(value)?'selected':''}>${escapeHtml(o.name)}</option>`).join('')}</select></label>`}
function formHtml(resource,row={}){if(resource==='customers')return field('Nome','name','text',row.name||'',true,'maxlength="160"')+field('E-mail','email','email',row.email||'')+field('Telefone','phone','tel',row.phone||'')+field('Endereço','address','text',row.address||'',false,'maxlength="500"');if(resource==='categories')return field('Nome','name','text',row.name||'',true,'maxlength="120"')+field('Descrição','description','textarea',row.description||'',false,'maxlength="500"');if(resource==='products')return selectField('Categoria','category_id',state.categories,row.category_id)+field('Nome','name','text',row.name||'',true,'maxlength="160"')+field('Descrição','description','textarea',row.description||'')+field('Valor','price','number',row.price??0,true,'min="0" step="0.01"')+field('Imagem (URL)','image_url','url',row.image_url||'')+`<label class="check"><input name="is_active" type="checkbox" ${row.is_active!==false?'checked':''}> Ativo</label>`;if(resource==='quotes')return selectField('Cliente','customer_id',state.customers,row.customer_id)+field('Descrição','description','textarea',row.description||'',true,'maxlength="3000"')+field('Valor total','total','number',row.total??0,true,'min="0" step="0.01"')+`<label>Status<select name="status"><option value="pending" ${row.status==='pending'||!row.status?'selected':''}>Pendente</option><option value="approved" ${row.status==='approved'?'selected':''}>Aprovado</option><option value="rejected" ${row.status==='rejected'?'selected':''}>Recusado</option></select></label>`;if(resource==='users')return field('Nome','name','text',row.name||'',true,'maxlength="120"')+field('E-mail','email','email',row.email||'',true)+`<label>Status<select name="is_active"><option value="true" ${row.is_active?'selected':''}>Ativo</option><option value="false" ${!row.is_active?'selected':''}>Inativo</option></select></label><label>Permissão<select name="is_admin"><option value="true" ${row.is_admin?'selected':''}>Administrador</option><option value="false" ${!row.is_admin?'selected':''}>Usuário</option></select></label>`}
async function openForm(resource,id=null){state.resource=resource;state.id=id;let row={};if(resource==='products'&&!state.categories.length)state.categories=await api('/categories?limit=100');if(resource==='quotes'&&!state.customers.length)state.customers=await api('/customers?limit=100');if(id)row=state.rows.find(x=>x.id===id)||await api(`${configs[resource].endpoint}/${id}`);$('#modal-title').textContent=`${id?'Editar':'Novo'} ${resource==='quotes'?'orçamento':resource==='customers'?'cliente':resource==='products'?'produto/projeto':resource==='categories'?'serviço/categoria':'usuário'}`;$('#item-form').innerHTML=`<div class="form-grid">${formHtml(resource,row)}</div><div class="modal-actions"><button type="button" class="btn secondary" onclick="closeModal()">Cancelar</button><button type="submit" class="btn primary">${id?'Salvar alterações':'Cadastrar'}</button></div>`;$('#modal').classList.remove('hidden');$('#modal').setAttribute('aria-hidden','false')}
function createItem(resource){openForm(resource)}function editItem(resource,id){openForm(resource,id)}function closeModal(){$('#modal').classList.add('hidden');$('#modal').setAttribute('aria-hidden','true');$('#item-form').innerHTML=''}
async function submitItem(e){e.preventDefault();const fd=new FormData(e.target),resource=state.resource,p={};for(const [k,v] of fd.entries())p[k]=v;if(resource==='products'){p.category_id=Number(p.category_id);p.price=Number(p.price);p.is_active=fd.has('is_active')}if(resource==='quotes'){p.customer_id=Number(p.customer_id);p.total=Number(p.total)}if(resource==='users'){p.is_active=p.is_active==='true';p.is_admin=p.is_admin==='true'}try{const endpoint=resource==='users'?`/admin/users/${state.id}`:state.id?`${configs[resource].endpoint}/${state.id}`:configs[resource].endpoint;const method=resource==='users'?'PATCH':state.id?'PUT':'POST';await api(endpoint,{method,body:p});closeModal();toast(state.id?'Alterações salvas com sucesso.':'Cadastro realizado com sucesso.');await loadResource(resource)}catch(err){toast(err.message,'error')}}
async function deleteItem(resource,id){if(!confirm('Excluir este registro?'))return;try{await api(`${configs[resource].endpoint}/${id}`,{method:'DELETE'});toast('Registro excluído.');await loadResource(resource)}catch(err){toast(err.message,'error')}}
async function boot(){setupPublic();setupAdmin();try{const me=await api('/me');if(me?.is_admin){state.user=me;enterAdmin()}}catch(_){} }
boot();
