"""ai usage and durable automation

Revision ID: 016_ai_automation
Revises: 015_trial_30_days
"""
from alembic import op
import sqlalchemy as sa


revision = '016_ai_automation'
down_revision = '015_trial_30_days'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('operation', sa.String(length=40), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=True),
    sa.Column('result', sa.String(length=30), nullable=False),
    sa.Column('error_code', sa.String(length=40), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('consumption', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ai_usage_tenant_created', 'ai_usage', ['tenant_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_ai_usage_tenant_id'), 'ai_usage', ['tenant_id'], unique=False)
    op.create_table('automation_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=180), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('available_at', sa.DateTime(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.String(length=80), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'retry', 'completed', 'failed')", name='ck_automation_status'),
    sa.CheckConstraint('attempts >= 0 AND max_attempts > 0', name='ck_automation_attempts'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'idempotency_key', name='uq_automation_tenant_key')
    )
    op.create_index('ix_automation_due', 'automation_jobs', ['status', 'available_at', 'id'], unique=False)
    op.create_index(op.f('ix_automation_jobs_tenant_id'), 'automation_jobs', ['tenant_id'], unique=False)
    op.add_column('activities', sa.Column('idempotency_key', sa.String(length=180), nullable=True))
    op.create_unique_constraint('uq_activity_tenant_key', 'activities', ['tenant_id', 'idempotency_key'])
    op.add_column('project_costs', sa.Column('idempotency_key', sa.String(length=128), nullable=True))
    op.add_column('project_costs', sa.Column('request_fingerprint', sa.String(length=64), nullable=True))
    op.create_unique_constraint('uq_cost_tenant_key', 'project_costs', ['tenant_id', 'idempotency_key'])
    op.add_column('quotes', sa.Column('technical_brief', sa.JSON(), nullable=True))
    op.add_column('quotes', sa.Column('human_reviewed', sa.Boolean(), server_default=sa.false(), nullable=False))
    op.alter_column('quotes', 'human_reviewed', server_default=None)
    op.add_column('quotes', sa.Column('idempotency_key', sa.String(length=128), nullable=True))
    op.add_column('quotes', sa.Column('request_fingerprint', sa.String(length=64), nullable=True))
    op.create_unique_constraint('uq_quote_tenant_key', 'quotes', ['tenant_id', 'idempotency_key'])
    op.add_column('subscriptions', sa.Column('provider_event_created', sa.Integer(), server_default='0', nullable=False))
    op.alter_column('subscriptions', 'provider_event_created', server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'provider_event_created')
    op.drop_constraint('uq_quote_tenant_key', 'quotes', type_='unique')
    op.drop_column('quotes', 'request_fingerprint')
    op.drop_column('quotes', 'idempotency_key')
    op.drop_column('quotes', 'human_reviewed')
    op.drop_column('quotes', 'technical_brief')
    op.drop_constraint('uq_cost_tenant_key', 'project_costs', type_='unique')
    op.drop_column('project_costs', 'request_fingerprint')
    op.drop_column('project_costs', 'idempotency_key')
    op.drop_constraint('uq_activity_tenant_key', 'activities', type_='unique')
    op.drop_column('activities', 'idempotency_key')
    op.drop_index(op.f('ix_automation_jobs_tenant_id'), table_name='automation_jobs')
    op.drop_index('ix_automation_due', table_name='automation_jobs')
    op.drop_table('automation_jobs')
    op.drop_index(op.f('ix_ai_usage_tenant_id'), table_name='ai_usage')
    op.drop_index('ix_ai_usage_tenant_created', table_name='ai_usage')
    op.drop_table('ai_usage')
    # ### end Alembic commands ###
